### ISSUE TITLE
[Error] 0 bit file when take photo

### ISSUE THREAD

**Issue by Toskan4134** [termux/termux-api#446] opened 2021-09-16 02:35 UTC
Hey, i'm having s trouble with TERMUX-CAMERA-PHOTO command due to the fact that each time I use it sends me an error and creates a 0 bit file instead lf the photo

I tried running it directly on termux and from tasker. Both gave me that error.

This is what i did and the file i got.
http://imgur.com/a/g9cS1s1

This is the code
```04.23.23/E FIRE PLUGIN: Termux / com.twofortyfouram.locale.intent.action.FIRE_SETTING: 7 bundle keys
04.23.23/E Termux: plugin comp: com.termux.tasker/com.termux.tasker.FireReceiver
04.23.23/E add wait type Plugin1 time 10
04.23.23/E add wait type Plugin1 done
04.23.23/E add wait task
04.23.33/E Error: null
```
Sorry for the Spanish messages

**Comment by agnostic-apollo** [comment] 2021-09-16 02:45
Duplicate of #435

**Closed** 2021-09-16 02:45 UTC
