### ISSUE TITLE
i am facing this problem on tsu

### ISSUE THREAD

**Issue by sahad1234black** [termux/termux-api#397] opened 2021-01-15 11:41 UTC
![Screenshot_2021-01-15-17-08-24](https://user-images.githubusercontent.com/71170303/104723092-a3001f00-5726-11eb-924d-dd387b799d6d.png)

**Comment by Grimler91** [comment] 2021-01-15 11:49
Duplicate of https://github.com/termux/termux-api/issues/396

**Closed by Grimler91** 2021-01-15 11:49 UTC
