### ISSUE TITLE
10x performance slowdown after microcode update 

### ISSUE THREAD

**Issue by hanyman7** [termux/termux-api#650] opened 2023-12-26 16:51 UTC
**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

* termux-api application version:
* termux-api package version (installed through apt):
* Android OS version:
* Device model:
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=32115
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main/ stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages-cf.termux.dev/apt/termux-x11/ x11 main
Updatable packages:
Listing...
termux-am/stable 0.7.1 all [upgradable from: 0.7.0]
termux-tools/stable 1.40.1 all [upgradable from: 1.40.0]
termux-tools version:
1.40.0
Android version:
14
Kernel build information:
Linux localhost 5.15.104-android13-3-27760517 #1 SMP PREEMPT Fri Dec 1 14:30:06 KST 2023 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-A546U
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.api versionCode:51

Additional info, when I ran log car I saw a nasty error: 

12-26 10:50:39.965 11945 11945 E app_process: Error reading named image component header for /system/framework/boot.art, error: Failed to open oat file '/system/framework/arm64/boot.oat' when validating it for image '/system/framework/boot.art': Invalid oat header for '/system/framework/boot.oat': Invalid oat version, expected 0x32333000, got 0x32333400.
12-26 10:50:39.965 11945 11945 E app_process: Could not create image space with image file '/system/framework/boot.art!/apex/com.android.art/etc/boot-image.prof!/system/etc/boot-image.prof:/system/framework/boot-framework-adservices.art'. Attempting to fall back to imageless running. Error was: Failed to open oat file '/system/framework/arm64/boot.oat' when validating it for image '/system/framework/boot.art': Invalid oat header for '/system/framework/boot.oat': Invalid oat version, expected 0x32333000, got 0x32333400.

**Comment by agnostic-apollo** [comment] 2023-12-26 16:59
Check https://github.com/termux/termux-api/issues/638#issuecomment-1868383070, it's caused by reverting back to `TermuxAm` instead of socket server for Android 14. Slow down will be fixed when next app update is released and temux-am-socket server changes are finalized.

>Additional info, when I ran log car I saw a nasty error:

`TermuxAm` is already passing `-Xnoimage-dex2oat`, so image building should be ignored. Report to Samsung to stop pushing broken builds if you want it fixed, not a termux issue.

**Closed by agnostic-apollo** 2023-12-26 16:59 UTC

**Comment by hanyman7** [comment] 2023-12-26 17:02
> Check [#638 (comment)](https://github.com/termux/termux-api/issues/638#issuecomment-1868383070), it's caused by reverting back to `TermuxAm` instead of socket server for Android 14. Slow down will be fixed when next app update is released and temux-am-socket server changes are finalized.
> 
> > Additional info, when I ran log car I saw a nasty error:
> 
> `TermuxAm` is already passing `-Xnoimage-dex2oat`, so image building should be ignored. Report to Samsung to stop pushing broken builds if you want it fixed, not a termux issue.

I agree 👍, it was fine until I downloaded the update, my other phones are still running 10x faster 😞

**Comment by hanyman7** [comment] 2023-12-26 17:16
> Check [#638 (comment)](https://github.com/termux/termux-api/issues/638#issuecomment-1868383070), it's caused by reverting back to `TermuxAm` instead of socket server for Android 14. Slow down will be fixed when next app update is released and temux-am-socket server changes are finalized.
> 
> > Additional info, when I ran log car I saw a nasty error:
> 
> `TermuxAm` is already passing `-Xnoimage-dex2oat`, so image building should be ignored. Report to Samsung to stop pushing broken builds if you want it fixed, not a termux issue.

I just uploaded the logs to Samsung about the mismatch in boot.oat and boot.art ?!?!

Thank you 🙏 for your help once again.

**Comment by agnostic-apollo** [comment] 2023-12-26 17:19
You are welcome. You could probably disable freezer and install older version of `termux-api-package` and update `termux-am` to latest and it should probably work.

**Comment by hanyman7** [comment] 2023-12-26 17:37
> You are welcome. You could probably disable freezer and install older version of `termux-api-package` and update `termux-am` to latest and it should probably work.

For the moment my Java Battery App loops in 17ms and sleeps about 980 / up to the next second intervals, so it's fine. 
I had a bash contained prototype/model with 0 forkexecs except for battery-info and my sleep duration was ~900ms. Now it's barely ~125ms up to the next EPOCHREALTIME full second
