### ISSUE TITLE
bluetooth

### ISSUE THREAD

**Issue by rteja** [termux/termux-api#264] opened 2019-05-05 10:42 UTC
**Feature description**
Like there is an API for wifi. An API to turn bluetooth on/off and to see all connected devices will be useful.

**Comment by Grimler91** [comment] 2019-05-05 10:55
Duplicate of https://github.com/termux/termux-app/issues/235 / https://github.com/termux/termux-api/issues/196

**Closed by Grimler91** 2019-05-05 10:55 UTC
