### ISSUE TITLE
Feature Request: Support of import private key into secure hardware with tergent

### ISSUE THREAD

**Issue by imlibra** [termux/termux-api#669] opened 2024-03-27 21:49 UTC
**Feature description**
Support of (wrap and) import external private key into secure hardware with libtergent.
**Reference implementation**

Have you checked if the feature is accessible through the Android API?
Yes

https://security.stackexchange.com/questions/242385/secure-way-to-hold-private-keys-in-the-android-app
https://stackoverflow.com/questions/39249856/import-encrypted-aes-key-into-android-keystore-and-store-it-under-new-alias
https://developer.android.com/training/articles/keystore#ImportingEncryptedKeys

Do you know of other open-source apps that has a similar feature as the one you want? (Provide links)
No

**Comment by agnostic-apollo** [comment] 2024-03-28 00:17
Duplicate of #550

**Closed by agnostic-apollo** 2024-03-28 00:17 UTC
