### ISSUE TITLE
Termux-locations gives no output... Still not fixed!

### ISSUE THREAD

**Issue by Xosrov** [termux/termux-api#310] opened 2019-12-15 07:46 UTC
I saw this issue opened in 2016, but it still persists and I can't find a solution...
Using termux-location yields an empty output, and any parameters i pass to it still make no difference, for example:
Using the -r last tag
`"API_ERROR": "Failed to get location"`
I've already granted access to termux-api for location and other applications work fine

**Comment by xeffyr** [comment] 2019-12-15 09:12
Closing as duplicate of https://github.com/termux/termux-api/issues/204.
If issue is not solved, that means that it is unknown where problem happens and how to fix it.

**Closed by xeffyr** 2019-12-15 09:13 UTC
