### ISSUE TITLE
Disable/enable mobile data

### ISSUE THREAD

**Issue by zero-systems** [termux/termux-api#389] opened 2020-12-13 13:01 UTC
**Feature description**
Termux api does not allow to disable or enable mobile data, while allows doing this with wifi.
Why so? Is not it possible to disable and enable mobile data using java calls?

**Background information**
`Have you checked if the feature is accessible through the android API?`
12y https://stackoverflow.com/questions/12281020/disable-mobile-data
15y https://stackoverflow.com/questions/31120082/latest-update-on-enabling-and-disabling-mobile-data-programmatically

**Comment by Grimler91** [comment] 2020-12-13 16:34
Your second link states that it is not possible: https://stackoverflow.com/a/53058929. 

Best we could do is to open the settings for the user (according to that answer).
Also duplicate of https://github.com/termux/termux-api/issues/222.

**Closed by Grimler91** 2020-12-13 16:34 UTC
Labels: API command request

**Comment by zero-systems** [comment] 2020-12-14 04:23
Is it possible to do this with root access?

**Comment by Grimler91** [comment] 2020-12-14 05:48
> Is it possible to do this with root access?

Yes, `svc data disable` works on my LOS 17.1 phone at least
