### ISSUE TITLE
Clipboard API incorrectly trims and appends whitespace

### ISSUE THREAD

**Issue by gracenoah** [termux/termux-api#195] opened 2018-07-08 18:37 UTC
On termux-clipboard-set, the clipboard contents get trimmed: 
https://sourcegraph.com/github.com/termux/termux-api@fbf628fefded3d5f21f4532961d732d892ddd629/-/blob/app/src/main/java/com/termux/api/util/ResultReturner.java#L60

On termux-clipboard-get a newline is added to the end of the clipboard contents here:
https://sourcegraph.com/github.com/termux/termux-api@fbf628fefded3d5f21f4532961d732d892ddd629/-/blob/app/src/main/java/com/termux/api/ClipboardAPI.java#L43:1

This results in the inability to copy whitespace: https://github.com/termux/termux-api/issues/112
as well as completely nonsensical behavior if using the termux clipboard as the default clipboard in vim/nvim.

If copying and pasting from vim using this clipboard API, the selection gets trimmed and newlines get insert into it when pasting. That means that if you try to copy and paste anything within the same line, it will break your line into multiple lines when you paste.

I hope that these issue can be trivially fixed by updating the two lines of code I pointed out. I'm not sufficiently familiar with the android toolchain and the termux build system to fix it myself, but if I don't see a response for a while, I might give it a shot because I'd really like to be able to share the clipboard with vim on my chromebook.

**Comment by gsf** [comment] 2018-08-27 15:02
As of #213 a newline is no longer appended.

Good catch on the whitespace trimming. I had noticed that issue in pasting as well but couldn't identify the root cause. Proposed PR at #215.

**Comment by fornwall** [comment] 2018-08-28 01:07
Thanks! This has now been fixed in version 0.27 of the Termux:API app, which has been released and should be available as an update shortly.

**Closed by fornwall** 2018-08-28 01:07 UTC
