### ISSUE TITLE
termux-camera-photo: honor 4c dark photos 

### ISSUE THREAD

**Issue by macsmac** [termux/termux-api#125] opened 2018-01-18 02:00 UTC
Using the latest termux and termux:api versions termux-camera-photo outputs very dark photos:

<img src="https://user-images.githubusercontent.com/18601048/35077016-ec6ab44c-fc1c-11e7-8ae0-950b706f333d.png" width="240px">

Actually if you up the contrast and brightness you can see a bit of it

<img src="https://user-images.githubusercontent.com/18601048/35077027-fa83660a-fc1c-11e7-81a1-7bcfca3f6e0f.png" width="240px">

**Comment by Grimler91** [comment] 2018-01-18 18:01
Probably duplicate of https://github.com/termux/termux-api/issues/52.

**Comment by Grimler91** [comment] 2018-01-26 07:52
Closing jn favour of #52.

**Closed by Grimler91** 2018-01-26 07:52 UTC
